[sources]
git_local = true
github = true
linear = true
user_input = true

[app]
days_since=1

[git_local]
roots=["path1", "path2", "path3"]
identities=["id1", "id2", "id3"]

[github]
identities=["id1", "id2", "id3"]

[llm]
provider="openai|anthropic|google|ollama" # openai|anthropic|google|ollama
model="model_name"
max_tokens="4000"